#!/usr/bin/env python3
"""Generate docs/TOOLS.md from the live MCP tool registry, and check the
README's counts against it.

Hand-written API tables drift. This project has been bitten by exactly that
three times already - a write guard listing functions Live had removed, a census
filename pinned to a version, a README claiming two test suites when there were
three. So the tool reference is generated from the registry itself and checked
in CI-style with --check.

Generation fixes TOOLS.md but not the README, which is prose and stays
hand-written - and drifted anyway (836a3bb corrects its tool and op counts).
So --check also asserts every number the README states about the tool registry
and the census. See CLAIMS.

  ./scripts/gen_docs.py           write docs/TOOLS.md
  ./scripts/gen_docs.py --check   exit 1 if TOOLS.md is stale or a README
                                  count disagrees with the registry/census
"""
import asyncio
import inspect
import json
import pathlib
import re
import sys
import textwrap

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
import mcp_server.server as S  # noqa: E402

OUT = REPO / "docs" / "TOOLS.md"
README = REPO / "README.md"

# Grouping is editorial - the registry has no notion of it. Any tool not
# matched falls into "Other", which is the signal to update this list.
GROUPS = [
    ("Discovery", ["lom_search", "lom_describe", "lom_canonical_path",
                   "lom_count", "lom_types", "lom_ping"]),
    ("Read / write", ["lom_get", "lom_set", "lom_call",
                      "lom_get_batch", "lom_set_batch", "lom_transaction"]),
    ("MIDI notes", ["clip_get_notes", "clip_add_notes", "clip_modify_notes",
                    "clip_remove_notes"]),
    ("Browser", ["browser_list", "browser_load"]),
    ("Automation", ["clip_envelope_get", "clip_envelope_insert_step",
                    "clip_envelope_clear"]),
    ("Arrangement", ["arrangement_list_clips", "arrangement_create_clip",
                     "arrangement_duplicate_clip"]),
    ("Observers", ["lom_observe", "lom_unobserve", "lom_observers",
                   "lom_unobserve_all", "lom_poll_events"]),
]


def signature(name):
    fn = getattr(S, name, None)
    if fn is None:
        return ""
    try:
        sig = inspect.signature(fn)
    except (TypeError, ValueError):
        return ""
    parts = []
    for p in sig.parameters.values():
        ann = getattr(p.annotation, "__name__", None) or (
            str(p.annotation).replace("typing.", "")
            if p.annotation is not inspect.Parameter.empty else "")
        s = p.name + (": " + ann if ann else "")
        if p.default is not inspect.Parameter.empty:
            s += " = %r" % (p.default,)
        parts.append(s)
    return "%s(%s)" % (name, ", ".join(parts))


def render():
    tools = {t.name: t for t in asyncio.run(S.mcp.list_tools())}
    grouped = {n for _, names in GROUPS for n in names}
    other = sorted(set(tools) - grouped)

    L = ["<!-- GENERATED by scripts/gen_docs.py - do not edit by hand. -->",
         "# Tool reference", "",
         "%d tools, generated from the running registry so it cannot drift."
         % len(tools), "",
         "Signatures and descriptions come from the source; regenerate with",
         "`./scripts/gen_docs.py` after changing any tool.", ""]

    L.append("## Index")
    L.append("")
    for title, names in GROUPS:
        present = [n for n in names if n in tools]
        if present:
            L.append("- **%s** — %s" % (title, ", ".join("`%s`" % n
                                                         for n in present)))
    if other:
        L.append("- **Other** — %s" % ", ".join("`%s`" % n for n in other))
    L.append("")

    sections = GROUPS + ([("Other", other)] if other else [])
    for title, names in sections:
        present = [n for n in names if n in tools]
        if not present:
            continue
        L.append("## %s" % title)
        L.append("")
        for n in present:
            L.append("### `%s`" % n)
            L.append("")
            sig = signature(n)
            if sig:
                L.append("```python")
                L.append(sig)
                L.append("```")
                L.append("")
            # Docstring bodies carry 4-space Python indentation, which
            # markdown would render as a code block. Dedent everything after
            # the summary line so prose reads as prose.
            raw = tools[n].description or ""
            head, _, rest = raw.strip().partition("\n")
            desc = head + ("\n" + textwrap.dedent(rest) if rest.strip() else "")
            L.append(desc if desc.strip() else "_No description._")
            L.append("")
    return "\n".join(L).rstrip() + "\n"


# The README's counts, and what each must equal. TOOLS.md cannot drift because
# it is generated; the README is hand-written and has drifted - 836a3bb exists
# only to correct these numbers. Every occurrence is checked, so two copies of
# the tool count cannot disagree with each other either.
#
# Regenerating the README is not the answer: it is prose, and prose is worth
# writing by hand. Asserting its numbers is.
CLAIMS = [
    (r"\b(\d+) (?:generic )?tools\b", "tool count"),
    (r"Live ([\d.]+) exposes", "census version"),
    (r"exposes \*\*(\d+) reachable types", "type count"),
    (r"reachable types / (\d+) members", "member count"),
]


def check_readme():
    """Assert the README's hand-written numbers against registry and census."""
    census = sorted((REPO / "baseline").glob("lom_census_*.json"))
    if not census:
        print("README: no census in baseline/; run scripts/census.py")
        return 1
    data = json.loads(census[-1].read_text())
    actual = {
        "tool count": len(asyncio.run(S.mcp.list_tools())),
        "census version": census[-1].stem[len("lom_census_"):],
        "type count": data["type_count"],
        "member count": data["totals"]["substantive"],
    }

    text = README.read_text()
    bad = []
    for pattern, label in CLAIMS:
        want = actual[label]
        found = re.findall(pattern, text)
        if not found:
            bad.append("%s: README makes no claim matching %s" % (label, pattern))
            continue
        wrong = sorted(set(f for f in found if str(f) != str(want)))
        if wrong:
            bad.append("%s: README says %s, actual is %s"
                       % (label, " and ".join(wrong), want))
    if bad:
        print("README is STALE:")
        for b in bad:
            print("  %s" % b)
        return 1
    print("README counts match (%d tools, Live %s: %d types / %d members)"
          % (actual["tool count"], actual["census version"],
             actual["type count"], actual["member count"]))
    return 0


def main():
    text = render()
    check = "--check" in sys.argv
    if check:
        if not OUT.exists():
            print("docs/TOOLS.md missing; run scripts/gen_docs.py")
            return 1
        if OUT.read_text() != text:
            print("docs/TOOLS.md is STALE; run scripts/gen_docs.py")
            return 1
        print("docs/TOOLS.md up to date")
        return check_readme()
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(text)
    print("wrote %s (%d lines)" % (OUT.relative_to(REPO),
                                   text.count("\n") + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
