#!/usr/bin/env python3
"""Generate docs/TOOLS.md from the live MCP tool registry.

Hand-written API tables drift. This project has been bitten by exactly that
three times already - a write guard listing functions Live had removed, a census
filename pinned to a version, a README claiming two test suites when there were
three. So the tool reference is generated from the registry itself and checked
in CI-style with --check.

  ./scripts/gen_docs.py           write docs/TOOLS.md
  ./scripts/gen_docs.py --check   exit 1 if it is out of date
"""
import asyncio
import inspect
import pathlib
import sys
import textwrap

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
import mcp_server.server as S  # noqa: E402

OUT = REPO / "docs" / "TOOLS.md"

# Grouping is editorial - the registry has no notion of it. Any tool not
# matched falls into "Other", which is the signal to update this list.
GROUPS = [
    ("Discovery", ["lom_search", "lom_describe", "lom_canonical_path",
                   "lom_count", "lom_types", "lom_ping"]),
    ("Read / write", ["lom_get", "lom_set", "lom_call",
                      "lom_get_batch", "lom_set_batch", "lom_transaction"]),
    ("MIDI notes", ["clip_get_notes", "clip_add_notes", "clip_modify_notes",
                    "clip_remove_notes"]),
    ("Browser", ["browser_list", "browser_load"]),
    ("Automation", ["clip_envelope_get", "clip_envelope_insert_step",
                    "clip_envelope_clear"]),
    ("Arrangement", ["arrangement_list_clips", "arrangement_create_clip",
                     "arrangement_duplicate_clip"]),
    ("Observers", ["lom_observe", "lom_unobserve", "lom_observers",
                   "lom_unobserve_all", "lom_poll_events"]),
]


def signature(name):
    fn = getattr(S, name, None)
    if fn is None:
        return ""
    try:
        sig = inspect.signature(fn)
    except (TypeError, ValueError):
        return ""
    parts = []
    for p in sig.parameters.values():
        ann = getattr(p.annotation, "__name__", None) or (
            str(p.annotation).replace("typing.", "")
            if p.annotation is not inspect.Parameter.empty else "")
        s = p.name + (": " + ann if ann else "")
        if p.default is not inspect.Parameter.empty:
            s += " = %r" % (p.default,)
        parts.append(s)
    return "%s(%s)" % (name, ", ".join(parts))


def render():
    tools = {t.name: t for t in asyncio.run(S.mcp.list_tools())}
    grouped = {n for _, names in GROUPS for n in names}
    other = sorted(set(tools) - grouped)

    L = ["<!-- GENERATED by scripts/gen_docs.py - do not edit by hand. -->",
         "# Tool reference", "",
         "%d tools, generated from the running registry so it cannot drift."
         % len(tools), "",
         "Signatures and descriptions come from the source; regenerate with",
         "`./scripts/gen_docs.py` after changing any tool.", ""]

    L.append("## Index")
    L.append("")
    for title, names in GROUPS:
        present = [n for n in names if n in tools]
        if present:
            L.append("- **%s** — %s" % (title, ", ".join("`%s`" % n
                                                         for n in present)))
    if other:
        L.append("- **Other** — %s" % ", ".join("`%s`" % n for n in other))
    L.append("")

    sections = GROUPS + ([("Other", other)] if other else [])
    for title, names in sections:
        present = [n for n in names if n in tools]
        if not present:
            continue
        L.append("## %s" % title)
        L.append("")
        for n in present:
            L.append("### `%s`" % n)
            L.append("")
            sig = signature(n)
            if sig:
                L.append("```python")
                L.append(sig)
                L.append("```")
                L.append("")
            # Docstring bodies carry 4-space Python indentation, which
            # markdown would render as a code block. Dedent everything after
            # the summary line so prose reads as prose.
            raw = tools[n].description or ""
            head, _, rest = raw.strip().partition("\n")
            desc = head + ("\n" + textwrap.dedent(rest) if rest.strip() else "")
            L.append(desc if desc.strip() else "_No description._")
            L.append("")
    return "\n".join(L).rstrip() + "\n"


def main():
    text = render()
    check = "--check" in sys.argv
    if check:
        if not OUT.exists():
            print("docs/TOOLS.md missing; run scripts/gen_docs.py")
            return 1
        if OUT.read_text() != text:
            print("docs/TOOLS.md is STALE; run scripts/gen_docs.py")
            return 1
        print("docs/TOOLS.md up to date")
        return 0
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(text)
    print("wrote %s (%d lines)" % (OUT.relative_to(REPO),
                                   text.count("\n") + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
